### ISSUE TITLE
node/validator process down

### ISSUE THREAD

**Issue by mcscrad** [Yoldark34/lighthouse-staking-dashboard#1]
Hello,

I cannot get the dashboard to find the bn or vn. I know my validator is up and working but the node isnt finding it. Any ideas why or how I can debug this?

I can get https://github.com/sigp/lighthouse-metrics/ to work.

Thanks

**Comment by Yoldark34** [comment]
Hello, 
Are you talking about the counters on the top right ? The alerts on the bottom right ? The counter on the Node ?

If you changed the name of your lighthouse instances (Settings => Variables => "node_job" and "validator_job") you need to manually change the query from the alerts 

![image](https://user-images.githubusercontent.com/3829890/120099981-a547a080-c13e-11eb-8e24-fae22c55fd3f.png)

As the alerts can't use variables, this is written by hand.
The alerts is the only place where you need to change job names.

**Comment by yawhide** [comment]
ok i understand now.

for anyone else who is confused, checked your granana.yml and use the `job_name` here for your beacon node and validators.

**Comment by Yoldark34** [comment]
I think it is solved. I close.

**Comment by gunnim** [comment]
Found the job names in prometheus.yml
