### ISSUE TITLE
Graph does not show new validators after large number is added

### ISSUE THREAD

**Issue by nicogranuja** [Yoldark34/lighthouse-staking-dashboard#7]
Hi Yoldark34,

Playing with the dashboards on a testnet, and found out that for some reason the dashboard stops adding new data frames after 62 validators... I don't know how to best explain it, best I can do is give an example and hope that can root cause the issue?

Anyway the `validator_monitor_balance_gwei` data frame when I query Prometheus only shows up to `62` validators  when there are actually more, I can accurately get the total number by just running `vc_validators_total_count` also, leads me to believe the data frames stop updating because the last 4 stay as `pending` even though they're not. 

Would there be any limits configured that prevent the rest of the validators from showing?

Thanks

**Comment by Yoldark34** [comment]
Hello,

I'm not aware of any limit.

And i don't know what can be the root cause.

Did you try to query the beacon chain directly to get the json response and see if all the data is in the json?

Also, since the withdrawal the graph are kind of broken. I' m looking into solutions for this problem... 

Best regards.

**Comment by nicogranuja** [comment]
Thanks for the prompt response, Yoldark32, 

I made the same request via Postman and the result was the same, all the panels that are dealing with validator data seem to be 'frozen' with the same results, even though I change the time frame for the last 5 minutes.

I am not sure if this issue is related to the known issue after the Shanghai upgrade, I don't believe it is directly related to it, before while the validators were going from `Pending` to `Active` the values were being updated accordingly, now most panels are static and not changing except for a few such as hardware usage and non validator related panels.

Anyways if you could think of something that I could test it would be great, if not that's OK we may close this issue since it might not even be the dashboards fault.

Thanks.

**Comment by nicogranuja** [comment]
### Solved issue
Since the merge of this PR on Lighhouse https://github.com/sigp/lighthouse/pull/3728 there has been a flag `--validator-monitor-individual-tracking-threshold ` with default value of `64`

In lighthouse codebase: `pub const DEFAULT_INDIVIDUAL_TRACKING_THRESHOLD: usize = 64;`

The flag prevents metrics being emitted when the validator instance is running more than 64 validators.

So for users who run more than `64` validators on their machine running lighthouse, the flag `--validator-monitor-individual-tracking-threshold {N}` needs to be passed where N is the number of validators that is > 64 otherwise no metrics are emitted per validator.

This flag addresses a Prometheus cardinality issue when running a lot of validators and keeping metrics enabled on them, since it might affect the running validator machine as long as the number of validators is high, we should run it at our own risk.
